### ISSUE TITLE
Do model pruning on Core

### ISSUE THREAD

**Issue by yav** [GaloisInc/ASKE-E#63]
When simulating DEqs we eliminate equations that have no effect on the measured result.  Currently this is done on the `DEQ.Syntax`, but a very similar algorithm should work for `Core`, so it'd be good to implement it at that level.  

If we had it in Core, we could remove it from DEq.  Technically, we have a path that goes to DEQ without going to Core (i.e., using the DEQ notation), but large models are likely to come in through core anyway, so not sure if we should keep it or simplify it away.

**Comment by RyanGlScott** [comment]
Are there existing examples of model pruning in the repo somewhere (in the test suite or otherwise) that one could use as a reference for how it should behave?

**Comment by yav** [comment]
Have a look at function `pruneEqns` in `L.A.DEQ.Simulate`.   Basically given a set of "roots"  (things that we'd like to compute) we look at all the equations that might affect them and keep those.  Then we add any of *their* dependencies to the root set and keep repeating until we reach a fixed point.   Any equations that did not get picket are removed because they don't affect the values of interest.

**Comment by RyanGlScott** [comment]
Right, I saw `pruneEqns`--I'm just wondering what the prototypical use case for pruning is (which model to prune, and which variables). Currently, there's no test coverage for this feature (as far as I can tell), so I want to make sure that I don't inadvertently break something when tinkering with it..

**Comment by yav** [comment]
The main example where something like this should help is simulating the rasmachine (`modelRepo/gromet-pnc/rasmachine...`).  It's in (classic) Petri net format, we convert it to Core, then to differential equations, then we do th epruning, then we simulate it with GSL.    It goes quite a bit faster with the pruning.    I think if we did the pruning at the Core level, then we might gain benefits when we simulate using the discrete event simulator, as in the case we don't use ODEs, and instead generate C++ from Core.

**Comment by samcowger** [comment]
This is realized, at least in part, in https://github.com/GaloisInc/ASKE-E/commit/baedc47c9a64e45904c5684a451db45c25630418. I haven't tested it for simulation speed on the rasmachine model yet, however. The algorithm differs slightly from `pruneEqns`, since it needed to be tailored to model events rather than state rates.
