### ISSUE TITLE
parse error renders the kernel non-responsive to subsequent commands

### ISSUE THREAD

**Issue by m10f** [GaloisInc/ASKE-E#93]
![Screenshot from 2021-08-05 14-45-47](https://user-images.githubusercontent.com/10691480/128425438-a0eae48d-376a-42c7-b81e-4b5718a81313.png)

**Comment by abakst** [comment]
I guess `donu`'s Exposure server shouldn't quit on parse errors and the like.

**Comment by abakst** [comment]
Should be fixed by #94

**Comment by abakst** [comment]
Closing due to the above...future errors should result in a new issue
